### ISSUE TITLE
Update redirects from https://cosmos.network to https://v1.cosmos.network

### ISSUE THREAD

**Issue by nylira** [cosmos/new-cosmos.network#39]
Pre-requisite: pointing the current cosmos.network website to the v1 subdomain

Important, otherwise about half of the 120 redirects will fail to work properly.

**Comment by lovincyrus** [comment]
https://github.com/cosmos/new-cosmos.network/pull/36/commits/0a91e5e560273d89dc63f91b6170b2717c342098
